### ISSUE TITLE
is_moving method always return 1 even if it's not actually moving

### ISSUE THREAD

**Issue by ohkura** [elephantrobotics/pymycobot#2]
I found the is_moving method always return 1 even when mycobot is not working.  I'm not sure it's an issue of this Python library or something else, but let me report here anyway.

my environment:
- myStudio 0.0.4
- MacOS 10.15.6
- pyserial 3.5
- pymycobot 2.1.2

**Comment by zlj-zz** [comment]
It doesn't matter. At present, `is_moving` is reserved. There is no real implementation, so atom only returns `1`. You need to wait for atom to update.
