### ISSUE TITLE
Unnecessary fix for is_servo_enable() in v2.5.8

### ISSUE THREAD

**Issue by 3110** [elephantrobotics/pymycobot#21]
**Describe the bug**
The fix 4b4a14419463067e6f788c77598688118bce9b66 is unneccesary. You have to fix the reply of is_servo_enable() from AtomMain v3.2 instead.

**To Reproduce**
AtomMain v3.2 replies the unnecessary joint number(6) for `is_servo_enable(6).` 
```
Sending:  fe fe 03 50 06 fa
Received: fe fe 04 50 06 01 fa
```

**Expected behavior**
```
Sending:  fe fe 03 50 06 fa
Received: fe fe 03 50 01 fa
```
Other commands that specify a joint number do not include it in their reply.

**Desktop:**
- myCobot-280(M5stack ver.)  
  - AtomMain v3.2
  - minirobot v0.4
- OS: Windows 11  
  - Python v3.9.6
  - pymycobot v2.5.8

**Comment by zlj-zz** [comment]
I'm not sure why, but that's what we designed.

**Comment by zlj-zz** [comment]
I asked my colleagues. This is used to confirm information and prevent loss during asynchronous communication.

**Comment by 3110** [comment]
Thanks, I understand what you intend to.
