### ISSUE TITLE
jog_coord not work

### ISSUE THREAD

**Issue by MasashiOhtake** [elephantrobotics/pymycobot#23]
**Describe the bug**
jog_coord() command not work in myCobot Pi

**To Reproduce**
from pymycobot.mycobot import MyCobot
from pymycobot.genre import Coord
from pymycobot.genre import Angle
from pymycobot import PI_PORT, PI_BAUD
import time
mc = MyCobot(PI_PORT, PI_BAUD)
mc.power_on()
mc.jog_coord(1,1,50)
time.sleep(1.5)

**Expected behavior**
my cobot move

**Desktop (please complete the following information):**
 - myCobotPi
 - OS: Raspbian GNU/LINUX 10 (buster)
        pymycobot 2.5.9
        python 2.7.16

**Additional context**
Using jog_angle command can move mycobot

**Comment by Eheech** [comment]
Sorry, we haven't release this function yet ... We suggest you use send_coord() or send_coords() first ...

**Comment by MasashiOhtake** [comment]
Thanks for your kind comment
