### ISSUE TITLE
Format for Sending and Receiving Command Frames not correct

### ISSUE THREAD

**Issue by markusbuchholz** [elephantrobotics/pymycobot#35]
**Format for Sending and Receiving Command Frames**

I refer to the documentation for development:
https://docs.elephantrobotics.com/docs/myCobot-en/3-development/6-communication.html

The format data is not clear:

1. Not sure how to send data to controller ion order ex :to move joint 2 by 20 deg
Used differetrt configuration of provided example:
Serial port sending example: FE FE 0F 22 06 E6 EA 4E C4 81 0B BD EA C0 02 B6 FA
But is seems there is not correct. Could you please specify how I should arrange the "string" to perform move joint 2 by 20 deg
 
2. While running the debugging mode and mycobot.get_angles() I can see the data format which I receive is not consistent with the provided documentation:
I expected to receive (similar) ex from documentation:
FE FE 0E 20 06 E6 EA 4E C4 81 0B BD EA C0 02 B6 FA

but I received:
11:51:10.354 DEBU [pymycobot.generate] _read: b'\xff\xff\x01\x04\x028\x02\xbe\xff\xff\x01\x04\x00\x03\x08\xef\xff\xff\x02\x04\x028\x02\xbd\xff\xff\x02\x04\x00\xc8\x07*\xff\xff\x03\x04\x028\x02\xbc\xff\xff\x03\x04\x00\xff\x07\xf2\xff\xff\x04\x04\x028\x02\xbb\xff\xff\x04\x04\x00\xfb\x07\xf5\xff\xff\x05\x04\x028\x02\xba\xff\xff\x05\x04\x00\xfd\x07\xf2\xff\xff\x06\x04\x028\x02\xb9\xff\xff\x06\x04\x00\x01\x08\xec\xff\xff\xfe\x0c\x83)\x07\x01\x00\x00\x08\x00\x00\x1a\x00\x1f\xff\xff\xfe\x0c\x83)\x07\x02\x008\x08\x00\x00\xe8\x03\x15\xff\xff\xfe\x0c\x83)\x07\x03\x00\x00\x08\x00\x00\x08\x00/\xff\xff\xfe\x0c\x83)\x07\x04\x00\x00\x08\x00\x00,\x00\n\xff\xff\xfe\x0c\x83)\x07\x05\x00\x00\x08\x00\x00\x1a\x00\x1b\xff\xff\xfe\x0c\x83)\x07\x06\x00\x00\x08\x00\x00\x08\x00,\xff\xff\x01\x04\x028\x02\xbe\xff\xff\x01\x04\x00\x03\x08\xef\xff\xff\x02\x04\x028\x02\xbd\xff\xff\x02\x04\x00\xc8\x07*\xff\xff\x03\x04\x028\x02\xbc\xff\xff\x03\x04\x00\xff\x07\xf2\xff\xff\x04\x04\x028\x02\xbb\xff\xff\x04\x04\x00\xfb\x07\xf5\xff\xff\x05\x04\x028\x02\xba\xff\xff\x05\x04\x00\xfd\x07\xf2\xff\xff\x06\x04\x028\x02\xb9\xff\xff\x06\x04\x00\x01\x08\xec\xfe\xfe\x0e \xff\xe6\x01\xec\xff\xf8\x00+\x00\x1a\xff\xf8\xfa'

Could you please provide more info how t read this data?

**Comment by anla-xu** [comment]
@markusbuchholz The last ones are the correct data `\xfe\xfe\x0e \xff\xe6\x01\xec\xff\xf8\x00+\x00\x1a\xff\xf8\xfa`

**Comment by markusZivid** [comment]
Thanks!
