### ISSUE TITLE
get_angles return empty

### ISSUE THREAD

**Issue by Kakcalu13** [elephantrobotics/pymycobot#39]
**Describe the bug**
Similar to https://github.com/elephantrobotics/pymycobot/issues/19, but this worked for the first time but then it stopped return data after that. Restart mycobot doesn't fix the issue.

**To Reproduce**
1. Go to '~/pymycobot/demo'
2. python3 basic.py
3. Enter all data like input of usb, baud and debug mode. After that, `get_angles()` should return data, not empty.
```

rpi@raspberrypi:~/pymycobot/demo $ python3 basic.py 

--------------------------------------------
| This file will test basic option method: |
|     set_led_color()                      |
|     send_angles()                        |
|     get_angles()                         |
|     send_angle()                         |
|     send_radians()                       |
|     get_radians()                        |
|     send_coords()                        |
|     get_coords()                         |
|     send_coord()                         |
--------------------------------------------
          

1 : /dev/ttyUSB0 - CP2104 USB to UART Bridge Controller - CP2104 USB to UART Bridge Controller
2 : /dev/ttyAMA0 - ttyAMA0

Please input 1 - 2 to choice:1
/dev/ttyUSB0

Please input baud(default:115200):115200
115200

Wether DEBUG mode[Y/n]:n

Start check basic options

::set_color() ==> color 255 255 0

::send_angles() ==> angles [0, 0, 0, 0, 0, 0], speed 100

::get_angles() ==> degrees: []

::send_angle() ==> angle: joint1, degree: 90, speed: 50

::send_radians() ==> set radians [1, 1, 1, 1, 1, 1], speed 100

::get_radians() ==> radians: []

::send_coords() ==> send coords [160, 160, 160, 0, 0, 0], speed 70, mode 0

::get_coords() ==> coords []

::send_coord() ==> send coord id: X, coord value: -40, speed: 70

::set_free_mode()

=== check end ===

```

**Expected behavior**
It should return the value of degree data

**Comment by wildangunawan** [comment]
Same issue using 280 Pi

**Comment by wildangunawan** [comment]
I already send this concern to the tech dept (support at elephantrobotics dot com) email. Hopefully we get response soon.

**Comment by anla-xu** [comment]
1.What is the probability that this problem occurs? Occasionally or all the time？

**Comment by wildangunawan** [comment]
> 1.What is the probability that this problem occurs? Occasionally or all the time？ 2.Please provide the model of the machine with the problem and the software version used (like atom's firmware version)

1. All the time.
2. myCobot 280 Pi 2020, need to check the software version but I think would be the latest one.

**Comment by anla-xu** [comment]
> > 1.出现这个问题的概率是多少？偶尔还是一直？ 2.请提供问题机器的型号和使用的软件版本（如atom的固件版本）
> 
> 1. 每时每刻。
> 2. myCobot 280 Pi 2020，需要检查软件版本，但我认为应该是最新的。

Can other interfaces be used? For example get_coords, is_power_on, The baud rate of 280 Pi is 1000000. Is this how you initialized it?
```
from pymycobot import MyCobot

mc = MyCobot('/dev/ttyAMA0', 1000000)
```

**Comment by wildangunawan** [comment]
> > > 1.出现这个问题的概率是多少？偶尔还是一直？ 2.请提供问题机器的型号和使用的软件版本（如atom的固件版本）
> > 
> > 
> > 
> > 1. 每时每刻。
> > 2. myCobot 280 Pi 2020，需要检查软件版本，但我认为应该是最新的。
> 
> Can other interfaces be used? For example get_coords, is_power_on, The baud rate of 280 Pi is 1000000. Is this how you initialized it?
> 
> ```
> from pymycobot import MyCobot
> 
> mc = MyCobot('/dev/ttyAMA0', 1000000)
> ```

Yes, others can be used but get_angles cannot. Considering we're playing with angles here, I think this is an important feature to have.

I initialized the myCobot using [this](https://github.com/elephantrobotics/pymycobot#source-code) `from pymycobot import PI_PORT, PI_BAUD # For raspberry pi version of mycobot.`

**Comment by anla-xu** [comment]
> > > > 1.出现这个问题的概率是多少？偶尔还是一直？ 2.请提供问题机器的型号和使用的软件版本（如atom的固件版本）
> > > 
> > > 
> > > 
> > > 1. 每时每刻。
> > > 2. myCobot 280 Pi 2020，需要检查软件版本，但我认为应该是最新的。
> > 
> > 
> > Can other interfaces be used? For example get_coords, is_power_on, The baud rate of 280 Pi is 1000000. Is this how you initialized it?
> > ```
> > from pymycobot import MyCobot
> > 
> > mc = MyCobot('/dev/ttyAMA0', 1000000)
> > ```
> 
> Yes, others can be used but get_angles cannot. Considering we're playing with angles here, I think this is an important feature to have.
> 
> I initialized the myCobot using [this](https://github.com/elephantrobotics/pymycobot#source-code)
> 
> ```
> from pymycobot import MyCobot
> from pymycobot import PI_PORT, PI_BAUD # For raspberry pi version of mycobot.
> mc = MyCobot(PI_PORT, PI_BAUD)
> ```

Please update pymycobot to the latest version, and add `debug=True` parameters during initialization to see if there is any data returned, please send me the running results
```
from pymycobot import MyCobot
from pymycobot import PI_PORT, PI_BAUD # For raspberry pi version of mycobot.
mc = MyCobot(PI_PORT, PI_BAUD, debug=True)
print(mc.get_angles())
```

**Comment by v-ghobadi** [comment]
Why get_angles() don't work for myCobot 280pi?

**Comment by anla-xu** [comment]
@Kakcalu13 Please provide the basic firmware, atom firmware and pymycobot version number you are using.

**Comment by michelle-aa-robotics-photonics** [comment]
I am also having this issue. I first was able to use the bot and extract the angles. Now I am not. The only change is that I updated myStudio and down
![Screenshot_20240701-160721](https://github.com/elephantrobotics/pymycobot/assets/173008148/13b2f359-6aa7-48a6-b60e-1899ff582087)
![PXL_20240701_192839664](https://github.com/elephantrobotics/pymycobot/assets/173008148/b52b1c5c-d2c3-4bbf-abbc-a05e3157d64b)
![PXL_20240701_192923729 (1)](https://github.com/elephantrobotics/pymycobot/assets/173008148/89718293-21f3-42ea-b239-acb2577ffa8e)
![PXL_20240701_193047574 MP](https://github.com/elephantrobotics/pymycobot/assets/173008148/e0d12b26-333c-4233-a66b-71e549ea1380)
![PXL_20240701_193212721](https://github.com/elephantrobotics/pymycobot/assets/173008148/6da254ef-034a-4a1f-932e-f80e7538beb8)
loaded the latest Atom firmware. I did not flash that firmware, though, because if I press the "Flash" button I get "Please connect the machine before burning". I checked the firmware and I have version 5.1.
