### ISSUE TITLE
Fresh Ubuntu 20 installation in RPi can't communicate with Atom

### ISSUE THREAD

**Issue by saratrajput** [elephantrobotics/pymycobot#40]
**Describe the bug**
I have installed Ubuntu 20 on a new SD card for the RPi of mycobotpi. I have installed pymycobot package with pip as well. But I'm not able to communicate with the robot and can't execute any motion.

I'm wondering what are the steps required when making a fresh Ubuntu installation on the RPi. Are there any packages that need to be installed? Where can I find more documentation regarding this.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saratrajput** [comment]
@anla-xu Thank you for your reply. It is the official system I downloaded myself. Is there a system provided by you as well? I wasn't aware of that. The OS on my original RPi was Raspbian Buster.

**Comment by anla-xu** [comment]
@saratrajput You can't directly use the official system of Raspberry Pi to control the mechanical arm. You need to reconfigure the serial port. You can try to search on Google: how to configure the serial port of Raspberry Pi, which may be difficult. The most effective way is to find after-sales customer service
