### ISSUE TITLE
get_angles always returns a fixed value

### ISSUE THREAD

**Issue by suresh-venkate** [elephantrobotics/pymycobot#43]
Hi,

I am using the MyCobot 280 Jetson Nano robot arm. I have initialized the interface in Python with the following commands:

from pymycobot.mycobot import MyCobot
mc = MyCobot('/dev/ttyTHS1',1000000)

When I run mc.get_angles(), the returned value is always: [180.08, 180.08, -180.08, 180.08, 180.08, 180.08]

Even after rotating various joints, mc.get_angles always returns: [180.08, 180.08, -180.08, 180.08, 180.08, 180.08]

Please let me know how this can be fixed.

**Comment by anla-xu** [comment]
Please use myStudio to re-burn the latest atom firmware to see if the problem is solved.
![image](https://github.com/elephantrobotics/pymycobot/assets/55946925/f3f15904-cb38-4ed4-a87c-e8442fa56b82)
