### ISSUE TITLE
unnecessary debug print

### ISSUE THREAD

**Issue by nisshan-x** [elephantrobotics/pymycobot#6]
**Describe the bug**
When I run pymycobot, unnecessary debug message appears on terminal.

```
���"L.jL��
12
���"L.jL��
12
���"L.jL��
12
���"L.jL��
12
���"L.jL��
12
���"L.jL��
12
���"L.jL��
```

**To Reproduce**
1. Update pymycobot to 2.2.0
2. Call get_radians() and send_radians()

**Expected behavior**
No debug message on terminal.

**Desktop (please complete the following information):**
 - OS: Ubuntu18.04
 - Version pymycobot 2.2.0, AtomMain2.5

**Additional context**
I found some `print` in your python script. Please remove it or add debug_enable argument.

**Comment by zlj-zz** [comment]
Thank you for reminding me. It was my mistake.
 I've removed the debug information and republished it. 
You can go further to 2.2.1
