### ISSUE TITLE
MyCobot 280 M5 - Bluetooth Not Implemented

### ISSUE THREAD

**Issue by Jonas-Metzger** [elephantrobotics/pymycobot#64]
Hi! I purchased the MyCobot in anticipation that I could connect to it via bluetooth. The pymycobot package currently only implements the bluetooth connection to MyBuddy, however. Would it be possible to add bluetooth support for the MyCobot M5 as well? 

Thank you very much.

**Comment by anla-xu** [comment]
Thank you for your feedback. Currently, there is no Bluetooth interface for 280M5 in pymycobot. This will be developed later. Please use the serial port or wifi to control the robot first.
