### ISSUE TITLE
OS on myCobot 280 Raspberry Pi sometimes slows down to be unusable

### ISSUE THREAD

**Issue by michelle-aa-robotics-photonics** [elephantrobotics/pymycobot#70]
**Describe the bug**
Whenever I am using the bot with an external monitor, after ~1 hour or so of usage, the response on the UI becomes extremely slow. I can move my mouse around, but the response to my clicks takes around 5 minutes.

**To Reproduce**
This time I
1. Used the bot for a few hours
2. Tried to download an update to the firmware
3. Download failed
4. UI slows down

**Expected behavior**
The OS remains responsive to my clicks (~a few seconds of delay max)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, as comes with Raspberry Pi
 - Browser Firefox

**Smartphone (please complete the following information):**

**Additional context**
I restarted the bot and it sped up again.

**Comment by anla-xu** [comment]
You can try to re-burn a system image, image download address: [Download](https://www.elephantrobotics.com/en/downloads/) . burning method: [burning](https://docs.elephantrobotics.com/docs/mycobot-pi-en/3-RobotKnowledge/3.5-ubuntu-system/3.5.1-SW-description.html)
