### ISSUE TITLE
Comment out common.py -> line 759

### ISSUE THREAD

**Issue by huber-sensoryx** [elephantrobotics/pymycobot#85]
**Describe the bug**
Thank you for the extensive Python library to communicate with your Robots!
We got the mechArm 270-M5 on the 9. of September, installed the newest API (vs 3.5.0) and wanted to communicate with our robot. However, every command that expected an return value gave back 'None'. After some going through the library code, we figure that the problem is the line 759 in the file common.py. After commenting it out, the responses started to make sense. 

**To Reproduce**
1. Set-up Python environment as documented by elephantrobotics
2. pip install pymycobot==3.5.0
3. run command such as `print(mc.get_angles())`
4. Output is None

**Expected behavior**
Get responses from the robot.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by anla-xu** [comment]
This issue has been fixed, please update to 3.5.1
